from enum import Enum


class VideoMetricType(str, Enum):
    LPIPS = "lpips"
    FID = "fid"
    FVD = "fvd"
    MSE = "mse"
    SSIM = "ssim"
    PSNR = "psnr"
    IS = "is"
    REAL_IS = "real_is"
    FVMD = "fvmd"
    VBENCH = "vbench"
    REAL_VBENCH = "real_vbench"
    #MET3R_LOOPED = "met3r_looped"
    LOOP_CONSISTENCY_LPIPS = "loop_consistency_lpips"
    LOOP_CONSISTENCY_SSIM = "loop_consistency_ssim"
    LOOP_CONSISTENCY_PSNR = "loop_consistency_psnr"
    LOOP_CONSISTENCY_MSE = "loop_consistency_mse"
    LOOP_CONSISTENCY_MET3R_COSINE = "loop_consistency_met3r_cosine"
    LOOP_CONSISTENCY_MET3R_LPIPS = "loop_consistency_met3r_lpips"
    LOOP_CONSISTENCY_MET3R_SSIM = "loop_consistency_met3r_ssim"
    LOOP_CONSISTENCY_MET3R_MSE = "loop_consistency_met3r_mse"
    LOOP_CONSISTENCY_MET3R_PSNR = "loop_consistency_met3r_psnr"
    TEMPORAL_CONSISTENCY_MET3R_COSINE = "temporal_consistency_met3r_cosine"
    TEMPORAL_CONSISTENCY_MET3R_LPIPS = "temporal_consistency_met3r_lpips"
    TEMPORAL_CONSISTENCY_MET3R_SSIM = "temporal_consistency_met3r_ssim"
    TEMPORAL_CONSISTENCY_MET3R_MSE = "temporal_consistency_met3r_mse"
    TEMPORAL_CONSISTENCY_MET3R_PSNR = "temporal_consistency_met3r_psnr"
    DEPTH_COLLISION = "depth_collision"

class VideoMetricModelType(str, Enum):
    LPIPS = "Lpips"
    INCEPTION_V3 = "InceptionV3"
    I3D = "I3D"
    PIPS = "PIPS"
    CLIP_B_32 = "CLIP_B_32"
    CLIP_L_14 = "CLIP_L_14"
    DINO = "DINO"
    LAION = "LAION"
    MUSIQ = "MUSIQ"
    RAFT = "RAFT"
    AMT_S = "AMT_S"
